---
- hosts: all
  become: true
  tasks:
    - hostname: name=postgresql
    - name: install OS packages for development
      yum: 
        name: 
          - libselinux-python
          - python-psycopg2
          - python-firewall
          - rh-postgresql10
          - rh-postgresql10-syspaths
          - bash-completion
          - vim
        state: latest
    - name: install OS elements
      yum: 
        name: '*' 
        state: latest
    - name: Initiate database
      become: true
      command: postgresql-setup --initdb
               creates=/var/opt/rh/rh-postgresql10/lib/pgsql/data/postgresql.conf

    - name: configure pg_hba.conf for local access
      replace: dest=/var/opt/rh/rh-postgresql10/lib/pgsql/data/pg_hba.conf 
                  regexp='^(local\s*\w*\s*\w*\s*)(peer)'
                  replace='\1trust' 
                  backup=yes
    - name: configure pg_hba.conf for network access
      replace: dest=/var/opt/rh/rh-postgresql10/lib/pgsql/data/pg_hba.conf 
               regexp='^(host\s*\w*\s*\w*\s*)(127.0.0.1/32)\s*(ident)'
               replace='\1 0.0.0.0/0        trust'
               backup=yes
    - name: configure postgresql.conf
      lineinfile:  path=/var/opt/rh/rh-postgresql10/lib/pgsql/data/postgresql.conf
                   regexp='^listen_addresses.*'
                   line="listen_addresses = '*'"
                   backup=yes
    - name: Start PostgreSQL and enable at boot
      service: name=postgresql
               enabled=yes
               state=started
    - name: create users in postgres
      vars:
        dbusers:
           - { username: shiftreservation, password: shiftreservation }
           - { username: root, password: smartvm }
           - { username: postgres, password: postgres }
           - { username: reservationbook , password: reservationbook }

      with_items: "{{ dbusers }}"
      postgresql_user: name={{ item.username }} password={{ item.password }} state=present role_attr_flags=SUPERUSER
    - name: reload postgresql
      service:
        name: postgresql
        state: restarted
        daemon_reload: yes
- hosts: all
  become: true
  tasks:
    - name: verify if we need to reboot
      command:  /usr/bin/needs-restarting
      register: reboot_needed
    - name: reboot machine and wait for it to come back
      reboot:
      when: reboot_needed.stdout != ""
...
